### ISSUE TITLE
ubuntu Build Supernode docker 

### ISSUE THREAD

**Issue by cnmeeia** [omniedgeio/docker-customize-supernode#1]
+ cd /tmp
+ git clone https://github.com/omniedgeio/n2n.git n2n
Cloning into 'n2n'...
+ cd n2n
+ git checkout none
error: pathspec 'none' did not match any file(s) known to git
The command '/bin/sh -c BUILD_DEPENDENCIES="         build-base         git         linux-headers         openssl-dev         bash         autoconf         automake     "; set -x     && apk add ${BUILD_DEPENDENCIES}     && cd /tmp     && git clone https://github.com/omniedgeio/n2n.git n2n     && cd n2n     && git checkout ${VERSION}     && ./autogen.sh     && ./configure     && make     && cp supernode /usr/bin/supernode     && apk del ${BUILD_DEPENDENCIES}     && rm -rf /var/cache/apk/*     && rm -rf /tmp/*' returned a non-zero code: 1

**Comment by yongqianme** [comment]
You need run 

```bash
curl https://raw.githubusercontent.com/omniedgeio/docker-customize-supernode/main/install.sh | bash
```

**Comment by cnmeeia** [comment]
Resolving deltas: 100% (27/27), done.
1) 2.6-stable-omni
2) 3.0-stable
3) Quit
Please enter your choice: invalid option echo $VERSION
Please enter your choice: invalid option sudo docker build  --build-arg VERSION=$VERSION -t docker-customize-supernode-$VERSION .
Please enter your choice: invalid option sudo docker run -d -p 443:443/udp docker-customize-supernode-$VERSION
Please enter your choice: invalid option sudo ufw allow 443
Please enter your choice: 


aoto skiping

**Comment by yongqianme** [comment]
input 1

**Comment by cnmeeia** [comment]
375c7ebe0137   docker-customize-supernode-3.0-stable   "/bin/sh -c '/usr/bi…"   22 seconds ago   Exited (0) 20 seconds ago             goofy_leavitt

**Comment by yongqianme** [comment]
Hi, I can not help you with such limited information. 
Can you provide the steps ? And 3.0 is not supported at the moment, you have to choose 1 to install 2.6-stable-omni. 
Be sure that your 443 port is open with your own VPS. 

Thanks.
